name: Validate New Entries

on:
  pull_request:
    branches: [main]
    paths:
      - "awesome_geophysics.json"
  push:
    paths:
      - "awesome_geophysics.json"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get previous version
        run: |
          git show HEAD^:awesome_geophysics.json > old.json
          [ -s old.json ] || echo '{"AwesomeGeophysics": {}}' > old.json

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run validation
        run: |
          python scripts/validate_new_entries.py old.json awesome_geophysics.json 2>&1 | while read line; do
            echo "::error::$line"
          done
